# Generated by Django 5.1.5 on 2025-02-09 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cliente_telefone_alter_itempedido_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.servico'),
        ),
    ]
